sudo: true
dist: xenial
language: python
addons:
  postgresql: "10"
env:
  global:
  - PGUSER=postgres
python:
  - "3.7.3"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - python manage.py test -v 2
