sudo: true
dist: xenial
language: python
addons:
  postgresql: "10"
env:
  global:
  - PGUSER=postgres
python:
  - "3.7.6" # Heroku
  # - "3.6.8" # EBS
install:
  - pip install -r requirements.txt
  # - Make sure FURY_AUTH is set in Travis to the Gemfury deployment key
  # - pip install -r requirements_private.txt
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - python manage.py test -v 2
# Deployment to EBS
# deploy:
#  - provider: elasticbeanstalk
#    access_key_id: $AWS_ACCESS_KEY_ID
#    secret_access_key:
#      secure: "$AWS_SECRET_ACCESS_KEY"
#    region: "eu-west-1"
#    app: ""
#    env: ""
#    bucket_name: "elasticbeanstalk-eu-west-1-637939682328"
#    on:
#      branch: master
